version: '3.1'

services:
  app:
    image: golang:1.22-alpine
    container_name: my_golang
    build:  .
    restart : always
    ports:
      - "3000:3000"


  postgres:
    image: postgres:alpine 
    container_name: kmutt
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: kmutt
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always